version: "3.4"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      # Project files
      - ./:/var/www/html:rw,cached
      # Nginx configuration for Symfony
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /var/www/html
    depends_on:
      - php
    tty: true

  php:
    build: docker/php
    volumes:
      # Project files
      - ./:/var/www/html:rw,cached
      # PHP configuration for Symfony
      - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
    tty: true
