version: "3.4"

services:
  nginx:
    image: nginx:alpine
    #ports: TODO
    volumes:
      # Project files
      - ./:/var/www/html:rw,cached
      # Nginx configuration for Symfony
      # - TODO
    depends_on:
      - php
    tty: true

  php:
    build: docker/php
    volumes:
      # Project files
      # - TODO
      # PHP configuration for Symfony
      - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
    tty: true
